keys:
  # each key has a coresponding ssh key

  - &users:
    - &admin age17j8hypc3ae5n3y2s20qv942ycnn33msrq3529t5zpv72mkvhgf4qx4n09e
    
    - &upidapi age1ehtnj2jqzrqz4dhy7d465d0nw80v7hnsddpygtgujyyerfjyjsvsf5q7e7

  - &hosts:
    - &upinix-pc age1jg86srj56t8khvv6enf3vuxyzv8ws5j7rwzy4ar2zyf082ytqcsq43s773

    - &upinix-laptop age1j35qp3h86grdkzk3m468gqcdpsvlsqnumakgpwc3jjt4a2cfweyqm4ewjl

    - &minimal-installer-x86_64 age13cn9z4c93t4wm6pr54g6sgl9jtllkljpu74nfxfq7py4vwq4c33swyw3hu

    - &full-installer-x86_64 age1pv4vess6fmduczjf82f9fzemumjugl67skye6hcwytqxd9kkx9dqatxyg7  

    # host keys stored in infra.yaml/${host name}
    # user keys stored in users/${user nane}.yaml/ssh-key

creation_rules:
  - path_regex: secrets/*
    key_groups:
      - age:
        - *admin
    
  # contans everything that is needed to setup all systems
  - path_regex: secrets/infra.yaml$
    key_groups:
      - age:
        - *admin

  - path_regex: secrets/users/upidapi$
    key_groups:
      - age:
          - *upinix-pc
          - *upinix-laptop

          - *upidapi
